#+title: Mathematical tidbits
#+author: [[file:../index.html][Vaibhav Karve]]
#+options: toc:1
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
#+subtitle: [[../index.html][Home]]

This is just a list of facts/definitions that didn't fit elsewhere.


* Homotopy
** Massey triple product
 If [α]⬝[β] = 0 ⇒ α⬝β = dσ.
 If [β]⬝[γ] = 0 ⇒ β⬝γ = dτ.
 Then define the triple product with
 ⟨α, β, γ⟩ = [σ⬝γ - α⬝τ]

- Keywords :: Operads, A_∞, E_∞. "More associative than (associative)
              rings. More commutative than commutative rings."

* Graph theory
Plabic graphs := planar bicolorable graphs.

* Quantum computing
** PAC learning model
- concept ≡ feature; c : X → {0, 1}
- concept class ≡ collection of features
- labelled examples (x, c(x))
- x ~ D, distribution on X
- given t samples (xᵢ, c(xᵢ)), i ∈ [t], compute with probability ≥
  1-δ, hypothesis c' such that Pr_{x~D}(c'(x) = c(x)) ≥ 1-ε.
- Interesting question to ask is what should be the size of t in terms
  of ε and δ?

_Note:_ a quantum version of sampling this distribution will look
like (assuming X is discrete):
$$|ψ\rangle = \sum_x \alpha_x |x, c(x)\rangle,$$
where $\alpha_x = \sqrt{D(x)}$.

* Stern sequence
  Bruce Reznick has some notes on these at [[https://faculty.math.illinois.edu/~reznick/595-ch1.pdf][link]].
  #+BEGIN_SRC lean :eval no
  def s : ℕ → ℕ
  | 0 := 0
  | 1 := 1
  | 2n := s(n)
  | 2n+1 := s(n) + s(n+1)  
  #+END_SRC
